"""Theme-aware post figures: the shared colour tokens and the render-time inliner.

ADR-0005 records the decision. In short: a post figure that carries the token
block below is inlined into the post HTML at render time instead of being
loaded through ``<img>``, so the CSS custom properties the site sets for its
light and dark themes reach the figure's fills and strokes. A figure without
the block still renders as ``<img>``, unchanged.

Every migrated SVG carries ``token_style_block()`` verbatim. Inside that block
the tokens are declared on ``svg:root``, which only matches when the SVG is
its own document (opened directly or loaded through ``<img>``); there the
figure follows the OS colour scheme. Inlined, the same selector matches
nothing and the page's values, keyed off the theme class Reflex puts on
``<html>``, win.

To migrate a figure, see ``scripts/theme_figure.py`` and ADR-0005.
"""

import html
import re
from pathlib import Path

ASSETS_DIR = Path(__file__).resolve().parent.parent / "assets"

# Token values per theme. Text-bearing tokens hold WCAG AA 4.5:1 against
# ``bg``; ``grid`` holds the 3:1 AA ratio for non-text graphics; ``ink`` holds
# 4.5:1 against every ``*-soft`` fill, which is the only text allowed on them.
# tests/test_figure_tokens.py computes all of these.
FIGURE_TOKENS: dict[str, dict[str, str]] = {
    "light": {
        "bg": "#f6f8fa",
        "ink": "#1f2328",
        "muted": "#59636e",
        "grid": "#818b98",
        "accent-1": "#0969da",
        "accent-2": "#a85200",
        "good": "#1a7f37",
        "bad": "#cf222e",
        "accent-3": "#8250df",
        "accent-1-soft": "#ddf4ff",
        "accent-2-soft": "#fff1e5",
        "accent-3-soft": "#fbefff",
        "good-soft": "#dafbe1",
        "bad-soft": "#ffebe9",
        "muted-soft": "#e6eaef",
    },
    "dark": {
        "bg": "#1f2020",
        "ink": "#cccccc",
        "muted": "#8f8f8f",
        "grid": "#707070",
        "accent-1": "#6cb6ff",
        "accent-2": "#d9894a",
        "good": "#7fb069",
        "bad": "#e07a5f",
        "accent-3": "#b083f0",
        "accent-1-soft": "#1d3a5c",
        "accent-2-soft": "#4a3418",
        "accent-3-soft": "#35284f",
        "good-soft": "#233d26",
        "bad-soft": "#4a2620",
        "muted-soft": "#333638",
    },
}

TEXT_TOKENS = ("ink", "muted", "accent-1", "accent-2", "accent-3", "good", "bad")
GRAPHIC_TOKENS = ("grid",)
SOFT_TOKENS = (
    "accent-1-soft",
    "accent-2-soft",
    "accent-3-soft",
    "good-soft",
    "bad-soft",
    "muted-soft",
)

TOKEN_BLOCK_MARKER = "fig-tokens v1"

_FIGURE_LINE = re.compile(r"^!\[(?P<alt>.*)\]\(/(?P<name>[\w.-]+\.svg)\)\s*$")
_FENCE = re.compile(r"^\s*(```|~~~)")


def _declarations(mode: str) -> str:
    return " ".join(f"--fig-{k}: {v};" for k, v in FIGURE_TOKENS[mode].items())


def token_style_block() -> str:
    """Return the exact ``<style>`` element every migrated SVG carries."""
    return (
        f"<style>/* {TOKEN_BLOCK_MARKER}: generated by "
        "src/alberto_codes_site/figures.py, do not edit */\n"
        f"    svg:root {{ {_declarations('light')} }}\n"
        "    @media (prefers-color-scheme: dark) {\n"
        f"      svg:root {{ {_declarations('dark')} }}\n"
        "    }\n"
        "  </style>"
    )


def figure_page_style() -> dict:
    """Return the page CSS that sets the tokens from the site's theme class."""

    def as_vars(mode: str) -> dict[str, str]:
        return {f"--fig-{k}": v for k, v in FIGURE_TOKENS[mode].items()}

    return {
        "& .post-figure": {
            **as_vars("light"),
            "margin": "1.5em 0",
        },
        ".dark & .post-figure": as_vars("dark"),
        "& .post-figure svg": {
            "display": "block",
            "max_width": "100%",
            "height": "auto",
            # Mermaid renders cap their own width below the column; centre them.
            "margin_inline": "auto",
        },
    }


def uses_tokens(svg_text: str) -> bool:
    """Return True when an SVG carries the current shared token block."""
    return token_style_block() in svg_text


def inline_figure_html(name: str, alt: str) -> str | None:
    """Return the inlined markup for a token-carrying figure, else None."""
    path = ASSETS_DIR / name
    if not path.is_file():
        return None
    svg = path.read_text()
    if not uses_tokens(svg):
        return None
    svg = re.sub(r"^\s*<\?xml[^>]*\?>\s*", "", svg)
    label = html.escape(alt, quote=True)
    return f'<div class="post-figure" role="img" aria-label="{label}">{svg}</div>'


def split_figures(body: str) -> list[tuple[str, str]]:
    """Split a post body into markdown runs and inlined theme-aware figures.

    Only an image line that stands alone as its own paragraph, outside any
    fenced code block, is lifted out; everything else stays markdown, so an
    un-migrated figure keeps rendering as ``<img>``.

    Returns:
        A list of ``("markdown", text)`` and ``("figure", html)`` pairs, in order.
    """
    lines = body.split("\n")
    segments: list[tuple[str, str]] = []
    pending: list[str] = []
    in_fence = False
    for i, line in enumerate(lines):
        if _FENCE.match(line):
            in_fence = not in_fence
        match = None if in_fence else _FIGURE_LINE.match(line)
        standalone = (i == 0 or not lines[i - 1].strip()) and (
            i == len(lines) - 1 or not lines[i + 1].strip()
        )
        figure = (
            inline_figure_html(match["name"], match["alt"])
            if match and standalone
            else None
        )
        if figure is None:
            pending.append(line)
            continue
        if "\n".join(pending).strip():
            segments.append(("markdown", "\n".join(pending)))
        pending = []
        segments.append(("figure", figure))
    if "\n".join(pending).strip():
        segments.append(("markdown", "\n".join(pending)))
    return segments
